### ISSUE TITLE
Weird behaviours with URLs

### ISSUE THREAD

**Issue by Prarog** [Phenitei/Wanna#3]
A command like this one, with complex (and totaly random..) URL provokes weird behaviors :

`wanna.sh -v buy https://www.amazon.fr/blue-herbal-pill-8000-jangyang/dp/B013L21M8W/ref=sr_1_1?ie=UTF8&qid=1469201451&sr=8-1&keywords=viagras`
My ouput for this particular example is :
```
[1] 921
[2] 922
[3] 923
[2]-  Done                    qid=1469201451
[3]+  Done                    sr=8-1
bash$ Checking for sqlite3 dependency... A-OK!
Checking sanity of given (or default) path: /Users/olivier/.wanna/wanna.db
inserting URL: https://www.amazon.fr/blue-herbal-pill-8000-jangyang/dp/B013L21M8W/ref=sr_1_1?ie=UTF8
inserting object type: 

[1]+  Done                    ./wanna.sh -v buy https://www.amazon.fr/blue-herbal-pill-8000-jangyang/dp/B013L21M8W/ref=sr_1_1?ie=UTF8
```

**Comment by Phenitei** [comment]
@Prarog:
That's normal and I can't do anything about it: it's because you didn't put your URL in single quotes; so your shell expands the whole command before launching wanna. The & character means launch a job in background, so here the shell interprets it as:
* execute 'wanna -v buy https://www.amazon.fr/blue-herbal-pill-8000-jangyang/dp/B013L21M8W/ref=sr_1_1?ie=UTF8' in the background (job [1]) and
* execute qid=1469201451 in the background (job [2]) and
* execute sr=8-1 in the background (job [3]) and
* execute keywords=viagras.
Which is exactly what happens: the environment variable keywords gets assigned to viagras in the foreground, so you see no output as it is not a verbose operation, jobs 2 and 3 that are also variable assignments complete, and then the (necessary longer) add to the database of the URL until the first & finishes. See man jobs (and ideally man bash).
I should probably add a reminder to quote input in the help output, otherwise the shell will indeed mangle any spaces and/or special characters.

(Also, WTF URL mate ><)
